import os
from typing import Dict

# API Keys
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")

# Model Settings
DEFAULT_MODEL_PROVIDER = "Google"
DEFAULT_MODEL_NAME = "gemini-2.0-flash"

# API Keys Dictionary
API_KEYS_DICT: Dict[str, str] = {
    "Google": GOOGLE_API_KEY,
}

# File Settings
ALLOWED_EXTENSIONS = {".pdf", ".docx"}
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB

# Database Settings
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./resume_portal.db")

# LLM Settings
LLM_TEMPERATURE = 0.7
LLM_MAX_TOKENS = 2000

# Skills List
SKILLS_LIST = [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "C++",
    "C#",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Go",
    "Rust",
    "Scala",
    "Perl",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Django",
    "Flask",
    "Spring",
    "Express.js",
    "Laravel",
    "Ruby on Rails",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Cassandra",
    "AWS",
    "Azure",
    "GCP",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Git",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "Travis CI",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Data Analysis",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Project Management",
    "Agile",
    "Scrum",
    "JIRA",
    "Confluence",
    "UI/UX Design",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Photoshop",
    "Technical Writing",
    "Documentation",
    "API Design",
    "REST",
    "GraphQL",
    "Testing",
    "Unit Testing",
    "Integration Testing",
    "Selenium",
    "Jest",
    "Security",
    "OAuth",
    "JWT",
    "SSL/TLS",
    "Penetration Testing",
    "DevOps",
    "Linux",
    "Shell Scripting",
    "Networking",
    "System Design",
    "Mobile Development",
    "iOS",
    "Android",
    "React Native",
    "Flutter",
    "Blockchain",
    "Smart Contracts",
    "Solidity",
    "Web3",
    "Ethereum",
    "Cloud Computing",
    "Serverless",
    "Microservices",
    "API Gateway",
    "Load Balancing",
    "Data Engineering",
    "ETL",
    "Data Warehousing",
    "Big Data",
    "Hadoop",
    "Natural Language Processing",
    "Computer Vision",
    "Speech Recognition",
    "Chatbots",
    "Game Development",
    "Unity",
    "Unreal Engine",
    "3D Modeling",
    "Animation",
    "AR/VR",
    "Augmented Reality",
    "Virtual Reality",
    "Mixed Reality",
    "IoT",
    "Embedded Systems",
    "Raspberry Pi",
    "Arduino",
    "Sensors",
    "Robotics",
    "Automation",
    "Control Systems",
    "Machine Vision",
    "Quantum Computing",
    "Quantum Algorithms",
    "Quantum Cryptography",
    "Bioinformatics",
    "Genomics",
    "Healthcare IT",
    "Medical Imaging",
    "FinTech",
    "Blockchain",
    "Cryptocurrency",
    "Trading Systems",
    "EdTech",
    "E-learning",
    "Learning Management Systems",
    "Educational Software",
    "GreenTech",
    "Renewable Energy",
    "Sustainability",
    "Environmental Monitoring",
    "SpaceTech",
    "Satellite Systems",
    "Space Exploration",
    "Astronomy",
    "Cybersecurity",
    "Network Security",
    "Application Security",
    "Cloud Security",
    "AI Ethics",
    "Responsible AI",
    "Bias Detection",
    "Fairness in AI",
    "Digital Marketing",
    "SEO",
    "SEM",
    "Social Media Marketing",
    "Content Marketing",
    "Business Intelligence",
    "Data Visualization",
    "Dashboard Design",
    "Reporting",
    "Supply Chain",
    "Logistics",
    "Inventory Management",
    "Procurement",
    "Human Resources",
    "Talent Management",
    "Recruitment",
    "HRIS",
    "Finance",
    "Accounting",
    "Financial Analysis",
    "Risk Management",
    "Legal Tech",
    "Contract Management",
    "Legal Research",
    "Compliance",
    "Real Estate Tech",
    "Property Management",
    "Real Estate Analytics",
    "Insurance Tech",
    "Claims Processing",
    "Risk Assessment",
    "Policy Management",
    "Healthcare Tech",
    "Electronic Health Records",
    "Telemedicine",
    "Health Analytics",
    "Retail Tech",
    "E-commerce",
    "Point of Sale",
    "Inventory Management",
    "Transportation Tech",
    "Fleet Management",
    "Route Optimization",
    "Logistics",
    "Energy Tech",
    "Smart Grid",
    "Energy Management",
    "Renewable Energy",
    "Manufacturing Tech",
    "Industry 4.0",
    "Smart Manufacturing",
    "Quality Control",
    "Construction Tech",
    "Building Information Modeling",
    "Project Management",
    "Agriculture Tech",
    "Precision Agriculture",
    "Smart Farming",
    "Crop Management",
    "Media Tech",
    "Content Management",
    "Digital Publishing",
    "Streaming",
    "Entertainment Tech",
    "Gaming",
    "Virtual Reality",
    "Augmented Reality",
    "Sports Tech",
    "Performance Analytics",
    "Fan Engagement",
    "Sports Management",
    "Travel Tech",
    "Booking Systems",
    "Travel Management",
    "Tourism",
    "Hospitality Tech",
    "Hotel Management",
    "Restaurant Management",
    "Customer Service",
    "Education Tech",
    "Learning Management",
    "Student Information Systems",
    "Government Tech",
    "E-Government",
    "Public Services",
    "Citizen Engagement",
    "Nonprofit Tech",
    "Donor Management",
    "Volunteer Management",
    "Fundraising",
    "Research Tech",
    "Laboratory Management",
    "Research Data Management",
    "Environmental Tech",
    "Environmental Monitoring",
    "Climate Analysis",
    "Urban Tech",
    "Smart Cities",
    "Urban Planning",
    "Infrastructure Management",
    "Social Impact Tech",
    "Social Innovation",
    "Community Development",
    "Disaster Management",
    "Emergency Response",
    "Crisis Management",
    "Security Tech",
    "Physical Security",
    "Access Control",
    "Surveillance",
    "Privacy Tech",
    "Data Privacy",
    "Compliance",
    "Security",
    "Ethics Tech",
    "Ethical AI",
    "Responsible Technology",
    "Governance",
    "Sustainability Tech",
    "Environmental Impact",
    "Resource Management",
    "Innovation Tech",
    "Research & Development",
    "Product Innovation",
    "Future Tech",
    "Emerging Technologies",
    "Technology Trends",
]
