# Name of the workflow
name: Deploy Talentsync

on:
  push:
    branches:
      - main

env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_PROJECT_PATH: ${{ secrets.VPS_PROJECT_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Navigating to project directory on VPS..."
            cd ${{ env.VPS_PROJECT_PATH }}

            echo "Pulling latest code from Git repository..."
            git pull origin main 

            echo "Rebuilding Docker images on VPS..."
            docker compose -f docker-compose.prod.yaml build

            echo "Bringing up services with new images..."
            docker compose -f docker-compose.prod.yaml up -d --force-recreate

            echo "Deployment complete!"
